name: Dev

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  # Run on PRs except for documentation
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v7,linux/arm64/v8,linux/amd64
  IMAGE_NAME: k9s
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get current commit on k9s submodule
        run: |
          echo K9S_COMMIT=$(git rev-parse --short @:./k9s) >> $GITHUB_ENV
          echo DATESTAMP=$(date +%Y.%m.%d) >> $GITHUB_ENV

      - name: Copy modified Dockerfile into k9s repo
        run: |
          rm ./k9s/Dockerfile
          cp ./Dockerfile ./k9s/Dockerfile

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build ${{ env.IMAGE_NAME }} image
        uses: docker/build-push-action@v4
        with:
          context: ./k9s
          build-args: |
            CGO_ENABLED=0
            K9S_COMMIT=${{ env.K9S_COMMIT }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.K9S_COMMIT }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.DATESTAMP }}
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:dev
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:${{ env.K9S_COMMIT }}
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:${{ env.DATESTAMP }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
